/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateLeagueArgs } from "./CreateLeagueArgs";
import { UpdateLeagueArgs } from "./UpdateLeagueArgs";
import { DeleteLeagueArgs } from "./DeleteLeagueArgs";
import { LeagueFindManyArgs } from "./LeagueFindManyArgs";
import { LeagueFindUniqueArgs } from "./LeagueFindUniqueArgs";
import { League } from "./League";
import { Country } from "../../country/base/Country";
import { LeagueService } from "../league.service";

@graphql.Resolver(() => League)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class LeagueResolverBase {
  constructor(
    protected readonly service: LeagueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "read",
    possession: "any",
  })
  async _leaguesMeta(
    @graphql.Args() args: LeagueFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [League])
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "read",
    possession: "any",
  })
  async leagues(@graphql.Args() args: LeagueFindManyArgs): Promise<League[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => League, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "read",
    possession: "own",
  })
  async league(
    @graphql.Args() args: LeagueFindUniqueArgs
  ): Promise<League | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => League)
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "create",
    possession: "any",
  })
  async createLeague(@graphql.Args() args: CreateLeagueArgs): Promise<League> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        country: args.data.country
          ? {
              connect: args.data.country,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => League)
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "update",
    possession: "any",
  })
  async updateLeague(
    @graphql.Args() args: UpdateLeagueArgs
  ): Promise<League | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          country: args.data.country
            ? {
                connect: args.data.country,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => League)
  @nestAccessControl.UseRoles({
    resource: "League",
    action: "delete",
    possession: "any",
  })
  async deleteLeague(
    @graphql.Args() args: DeleteLeagueArgs
  ): Promise<League | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Country, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Country",
    action: "read",
    possession: "any",
  })
  async country(@graphql.Parent() parent: League): Promise<Country | null> {
    const result = await this.service.getCountry(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
